"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import firebase_admin
from firebase_admin import credentials, firestore
import os
import json

# Corrige o caminho do firebase_key.json para ser relativo ao BASE_DIR
BASE_DIR = Path(__file__).resolve().parent.parent
cred_path = os.path.join(BASE_DIR, 'core', 'firebase_key.json')

# Inicializa o Firebase a partir da variável de ambiente FIREBASE_SERVICE_ACCOUNT (JSON string)
# Se a variável não existir, tenta carregar o arquivo `core/firebase_key.json` quando presente e não vazio.
cred = None
sa_json = os.environ.get('FIREBASE_SERVICE_ACCOUNT')
if sa_json:
    try:
        # pode ser uma string JSON; carregar para dict e passar para Certificate
        sa_dict = json.loads(sa_json)
        # debug: report size but never print secrets
        try:
            print(f"[startup] FIREBASE_SERVICE_ACCOUNT env present (json length={len(sa_json)}).", flush=True)
        except Exception:
            pass
        cred = credentials.Certificate(sa_dict)
    except Exception:
        # se falhar ao parsear, ignore e tentaremos o arquivo
        try:
            print("[startup] FIREBASE_SERVICE_ACCOUNT env present but failed to parse JSON.", flush=True)
        except Exception:
            pass
        cred = None

if cred is None:
    try:
        if os.path.exists(cred_path) and os.path.getsize(cred_path) > 0:
            cred = credentials.Certificate(cred_path)
    except Exception:
        cred = None

if cred:
    try:
        firebase_admin.initialize_app(cred)
        # instancia do Firestore
        db = firestore.client()
        try:
            print("[startup] Firebase initialized successfully.", flush=True)
        except Exception:
            pass
    except Exception as e:
        # initialization failed; log and continue without Firebase
        try:
            print(f"[startup] Firebase initialize_app failed: {e}", flush=True)
        except Exception:
            pass
        db = None
else:
    # Não inicializamos o Firebase automaticamente se não houver credenciais válidas.
    # Isso evita que o processo falhe no startup; confirme que a variável
    # FIREBASE_SERVICE_ACCOUNT está definida no ambiente do Railway.
    db = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rr!298*rd1gtpnnbdq0tr2i0=n@0pa4%(8z2ll@xo-r*gh8iyo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Permitir acesso por hosts configuráveis via variável de ambiente.
# Em produção configure a variável `ALLOWED_HOSTS` no Railway (ex: "medify-production-416a.up.railway.app,example.com").
default_allowed = '10.194.23.207,localhost,127.0.0.1,192.168.56.1'
raw_allowed = os.environ.get('ALLOWED_HOSTS', default_allowed)
# split and strip, ignore empty entries
ALLOWED_HOSTS = [h.strip() for h in raw_allowed.split(',') if h.strip()]

# CSRF trusted origins: can be set explicitly via env var `CSRF_TRUSTED_ORIGINS`
# value should be comma-separated full origins (including scheme), e.g.
# "https://medify-production-416a.up.railway.app,https://example.com"
raw_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS')
if raw_csrf:
    CSRF_TRUSTED_ORIGINS = [u.strip() for u in raw_csrf.split(',') if u.strip()]
else:
    # derive basic trusted origins from ALLOWED_HOSTS when possible
    CSRF_TRUSTED_ORIGINS = []
    for h in ALLOWED_HOSTS:
        # skip wildcards, localhost and IPs
        if h == '*' or h.startswith('127.') or h == 'localhost' or h.replace('.', '').isdigit():
            continue
        CSRF_TRUSTED_ORIGINS.append(f'https://{h}')

# Tell Django to trust X-Forwarded-Proto header from the proxy (Railway)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'medify_web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # custom session security middleware (idle/absolute timeouts)
    'medify_web.middleware.session_security.SessionSecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # expose DEFAULT_AI_MODEL to all templates
                'medify_web.context_processors.default_ai_model',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL prefix for static files. Must start and end with '/'.
STATIC_URL = '/static/'

# Allow configuring STATIC_ROOT via environment (set in Dockerfile as /vol/static)
STATIC_ROOT = os.environ.get('STATIC_ROOT', str(BASE_DIR / 'staticfiles'))

# Use WhiteNoise to serve static files in production (installed in requirements)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (user uploads)
# Files uploaded by users (profile photos etc.) will be saved to BASE_DIR / 'media'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session security settings
# Session cookie age (default 7 days). This is the absolute cookie max age.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days
# Make session cookie HttpOnly and SameSite for safer defaults
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
# In production, set this to True (requires HTTPS)
SESSION_COOKIE_SECURE = False

# CSRF cookie settings
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Whether to expire the session at browser close (False keeps session until age)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# If True, each request will refresh session expiry (sliding expiration)
# Set to False to avoid a DB write on every request; the middleware updates
# last-activity only when necessary (reduces I/O on SQLite during dev).
SESSION_SAVE_EVERY_REQUEST = False

# Granularity (seconds) for updating the session last-activity timestamp.
# This prevents the middleware from writing to the session on every single
# request. Adjust as needed for your environment.
SESSION_LAST_ACTIVITY_GRANULARITY = 60  # update last_activity at most once per minute

# Idle timeout (in seconds) - middleware will log out users after this inactivity
SESSION_IDLE_TIMEOUT = 60 * 30  # 30 minutes
# Absolute maximum session lifetime (in seconds)
SESSION_ABSOLUTE_TIMEOUT = 60 * 60 * 24 * 7  # 7 days

# Security hardening flags (set to True in production)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Default AI model configuration (central switch to select model for clients)
# Set to 'claude-haiku-4.5' to enable Claude Haiku 4.5 for all clients by default.
DEFAULT_AI_MODEL = 'claude-haiku-4.5'
