"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import json
from pathlib import Path
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# Security from env
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = [
    '*',
    os.environ.get("RAILWAY_PUBLIC_DOMAIN", ""),
    os.environ.get("RAILWAY_PRIVATE_DOMAIN", ""),
]
from pathlib import Path
import os
import json
import base64

import firebase_admin
from firebase_admin import credentials, firestore
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicialização do Firebase (tenta carregar a partir da variável de ambiente
# FIREBASE_SERVICE_ACCOUNT; em fallback usa o arquivo local core/firebase_key.json)
firebase_sa = os.environ.get('FIREBASE_SERVICE_ACCOUNT')
cred = None
if firebase_sa:
    try:
        # tenta interpretar como JSON
        cred_dict = json.loads(firebase_sa)
    except Exception:
        # se não for JSON, tenta base64 decode
        try:
            cred_json = base64.b64decode(firebase_sa).decode('utf-8')
            cred_dict = json.loads(cred_json)
        except Exception:
            cred_dict = None

    if cred_dict:
        cred = credentials.Certificate(cred_dict)
else:
    cred_path = os.path.join(BASE_DIR, 'core', 'firebase_key.json')
    if os.path.exists(cred_path):
        cred = credentials.Certificate(cred_path)

if cred:
    try:
        firebase_admin.initialize_app(cred)
        db = firestore.client()
    except Exception:
        db = None
else:
    db = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'medify_web',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # custom session security middleware (idle/absolute timeouts)
    'medify_web.middleware.session_security.SessionSecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # expose DEFAULT_AI_MODEL to all templates
                'medify_web.context_processors.default_ai_model',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default='sqlite:///db.sqlite3')
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads)
# Files uploaded by users (profile photos etc.) will be saved to BASE_DIR / 'media'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session security settings
# Session cookie age (default 7 days). This is the absolute cookie max age.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days
# Make session cookie HttpOnly and SameSite for safer defaults
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
# In production, set this to True (requires HTTPS)
SESSION_COOKIE_SECURE = False

# CSRF cookie settings
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Whether to expire the session at browser close (False keeps session until age)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# If True, each request will refresh session expiry (sliding expiration)
# Set to False to avoid a DB write on every request; the middleware updates
# last-activity only when necessary (reduces I/O on SQLite during dev).
SESSION_SAVE_EVERY_REQUEST = False

# Granularity (seconds) for updating the session last-activity timestamp.
# This prevents the middleware from writing to the session on every single
# request. Adjust as needed for your environment.
SESSION_LAST_ACTIVITY_GRANULARITY = 60  # update last_activity at most once per minute

# Idle timeout (in seconds) - middleware will log out users after this inactivity
SESSION_IDLE_TIMEOUT = 60 * 30  # 30 minutes
# Absolute maximum session lifetime (in seconds)
SESSION_ABSOLUTE_TIMEOUT = 60 * 60 * 24 * 7  # 7 days

# Security hardening flags (set to True in production)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Default AI model configuration (central switch to select model for clients)
# Set to 'claude-haiku-4.5' to enable Claude Haiku 4.5 for all clients by default.
DEFAULT_AI_MODEL = 'claude-haiku-4.5'
